Added class Comic. Just approximate structure.
IlyaYakubov/ComicShop pull request #1
Opened 2021-04-26 20:51 UTC by IlyaYakubov

2021-04-27 12:47 UTC, IlyaYakubov commented
1. Добавлено меню из одного пункта.
2. Добавлен метод добавления данных комикса в файл.

2021-05-13 10:32 UTC, revers-back commented
1. Выкачал проект - не запускается 
![изображение](https://user-images.githubusercontent.com/18118048/118113475-09ecc680-b3ef-11eb-8737-bea9dd1e5830.png)
формально дальше могу не смотреть 
тестируйте запуск с "нуля"
2.  Comic является одновременно и доменной моделью и классам, который парсит данный
Нужно отделить одно от другого
Принцип единственной ответственности
https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8

3.IFunctions из названия не понятно чем занимается

4. Store таже штука что и в 2 
класс занимается всем подпряд

5. Меню отделено - это хорошо
6. Почитать про MVP и попробовать сделать что-то наподобие, тема этой лекции будет позже 
7. Зачем джарник в проекте? 
8.     public static final BufferedReader CONSOLE_READER = new BufferedReader(new InputStreamReader(System.in));переменная не используется. Неиспользуемых переменных в коде быть не должно

2021-05-13 10:33 UTC, revers-back requested changes
См еще коммет с картинкой
    Выкачал проект - не запускается
    изображение
    формально дальше могу не смотреть
    тестируйте запуск с "нуля"
    Comic является одновременно и доменной моделью и классам, который парсит данный
    Нужно отделить одно от другого
    Принцип единственной ответственности
    https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8

3.IFunctions из названия не понятно чем занимается

    Store таже штука что и в 2
    класс занимается всем подпряд

    Меню отделено - это хорошо

    Почитать про MVP и попробовать сделать что-то наподобие, тема этой лекции будет позже

    Зачем джарник в проекте?

    public static final BufferedReader CONSOLE_READER = new BufferedReader(new InputStreamReader(System.in));переменная не используется. Неиспользуемых переменных в коде быть не должно

Merge state

A

2021-05-13 14:07 UTC, revers-back commented
каждый класс должен иметь комментарий в javadoc + каждый публичный метод

2021-05-13 14:12 UTC, revers-back commented
Прикрутить UI swing или JavaFx

2021-05-21 14:39 UTC, merged